-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

CREATE TABLE IF NOT EXISTS public.etudiant
(
    id integer NOT NULL,
    etu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    prom character varying(50) COLLATE pg_catalog."default" DEFAULT NULL::character varying,
    CONSTRAINT etudiant_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.examen
(
    id integer NOT NULL,
    session character varying(50) COLLATE pg_catalog."default" NOT NULL,
    code_matiere character varying(50) COLLATE pg_catalog."default" NOT NULL,
    sem character varying(10) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT examen_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.matiere
(
    id integer NOT NULL,
    code_matiere character varying(50) COLLATE pg_catalog."default" NOT NULL,
    nom character varying(255) COLLATE pg_catalog."default" NOT NULL,
    credit integer NOT NULL,
    CONSTRAINT matiere_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.note
(
    id integer NOT NULL,
    id_exam integer NOT NULL,
    etu character varying(50) COLLATE pg_catalog."default" NOT NULL,
    value double precision NOT NULL,
    CONSTRAINT note_pkey PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS public.note
    ADD CONSTRAINT fk_cfbdfa14b39bbac4 FOREIGN KEY (id_exam)
    REFERENCES public.examen (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_cfbdfa14b39bbac4
    ON public.note(id_exam);

END;